// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	jwt "github.com/dgrijalva/jwt-go"
	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// IJwtService is an autogenerated mock type for the IJwtService type
type IJwtService struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: user_id, userEmail, userRole
func (_m *IJwtService) GenerateToken(user_id primitive.ObjectID, userEmail string, userRole string) (string, error) {
	ret := _m.Called(user_id, userEmail, userRole)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(primitive.ObjectID, string, string) (string, error)); ok {
		return rf(user_id, userEmail, userRole)
	}
	if rf, ok := ret.Get(0).(func(primitive.ObjectID, string, string) string); ok {
		r0 = rf(user_id, userEmail, userRole)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(primitive.ObjectID, string, string) error); ok {
		r1 = rf(user_id, userEmail, userRole)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateToken provides a mock function with given fields: tokenString
func (_m *IJwtService) ValidateToken(tokenString string) (*jwt.Token, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 *jwt.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*jwt.Token, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) *jwt.Token); ok {
		r0 = rf(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jwt.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIJwtService creates a new instance of IJwtService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIJwtService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IJwtService {
	mock := &IJwtService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
