// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IPasswordService is an autogenerated mock type for the IPasswordService type
type IPasswordService struct {
	mock.Mock
}

// CheckPassword provides a mock function with given fields: existingUserPassword, userPassword
func (_m *IPasswordService) CheckPassword(existingUserPassword string, userPassword string) error {
	ret := _m.Called(existingUserPassword, userPassword)

	if len(ret) == 0 {
		panic("no return value specified for CheckPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(existingUserPassword, userPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HashPassword provides a mock function with given fields: userPassword
func (_m *IPasswordService) HashPassword(userPassword string) ([]byte, error) {
	ret := _m.Called(userPassword)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(userPassword)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(userPassword)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userPassword)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIPasswordService creates a new instance of IPasswordService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPasswordService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPasswordService {
	mock := &IPasswordService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
