// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	domain "task_management/Domain"

	mock "github.com/stretchr/testify/mock"
)

// IUserRepository is an autogenerated mock type for the IUserRepository type
type IUserRepository struct {
	mock.Mock
}

// CheckUserExists provides a mock function with given fields: user
func (_m *IUserRepository) CheckUserExists(user domain.User) (bool, domain.User) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CheckUserExists")
	}

	var r0 bool
	var r1 domain.User
	if rf, ok := ret.Get(0).(func(domain.User) (bool, domain.User)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(domain.User) bool); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(domain.User) domain.User); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Get(1).(domain.User)
	}

	return r0, r1
}

// Register provides a mock function with given fields: user
func (_m *IUserRepository) Register(user domain.User) (string, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.User) (string, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(domain.User) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(domain.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserRole provides a mock function with given fields: email, newRole
func (_m *IUserRepository) UpdateUserRole(email string, newRole string) error {
	ret := _m.Called(email, newRole)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(email, newRole)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIUserRepository creates a new instance of IUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUserRepository {
	mock := &IUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
