name: Go CI

on:
  # Trigger the workflow on push events for the "main" branch.
  push:
    branches: [ "main" ]
  # Trigger the workflow on pull request events targeting the "main" branch.
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: go get .

      - name: Run tests
        run: go test -v ./...